### ISSUE TITLE
fxpixiv.net stopped working

### ISSUE THREAD

**Issue by NamelessContributor** [IOIIIO/FxPixiv#1]
Posting a link like https://www.fxpixiv.net/artworks/106288996 in Discord shows no embed and visiting the link returns `Internal Server Error`.

Edit: Today (March 20) it is half-working but the embed still doesn't show an image.

**Comment by FizzBuzz3000** [comment]
Can confirm that fxpixiv is indeed broken with some internal server error, as just going to `https:///fxpixiv.net` shows the default NGINX welcome HTML

**Comment by Kaleidosium** [comment]
@NamelessContributor Since it seems like the author abandoned the project, I found an alternative that seems to work. https://github.com/HazelTheWitch/phixiv

https://www.phixiv.net/artworks/106288996

**Comment by NamelessContributor** [comment]
Currently the site is working again and an alternative exists in case it stops working once more.
